Add app ratings, create test for ratings and tasks
Reagent992/ipr-hackathon-yandex-alfa pull request #21
Opened 2024-01-26 17:53 UTC by greenpandorik

1. Создал app/ratings , модель + api + тесты
2. Написал тесты базовые для tasks
3. Доделал api tasks

2024-01-26 17:59 UTC, greenpandorik commented
4. Вынес константы в settings

2024-01-26 20:38 UTC, Reagent992 requested changes
Отличная работа💪 Тесты ⭐
Оставил комментарии, ничего критичного, лишние файлы только убрать из обязательного.

2024-01-26 20:38 UTC, Reagent992 commented on data_dump.json
> +[{"model": "admin.logentry", "pk": 1, "fields": {"action_time": "2024-01-21T20:49:41.920Z", "user": 1, "content_type": 11, "object_id": "2", "object_repr": "Volkov Mikhail ", "action_flag": 1, "chang
Полные фикстуры это конечно хорошо, но в момент когда сформировалась бд.
Давай пока сделаем папку `./docs/fixture` и туда зальем фикстуры, но только по своей модели.
Команда: `python -Xutf8 manage.py dumpdata название_приложения.название_модели  --indent=2 --output  docs/fixture/название_файла.json`  # вставить свое.
-Xutf8  добавляет поддержку русского языка
--indent=2 делает фикстуру "человеко-читаемой".
https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-dumpdata

2024-01-26 20:38 UTC, Reagent992 commented on ipr/migrations/0001_initial.py
> +# Generated by Django 5.0.1 on 2024-01-26 15:54
Изменяешь "чужой файл миграции".
Хотя файла миграции в `main` я бы не хотел видеть сейчас совсем, без него пока легче.

2024-01-26 20:38 UTC, Reagent992 commented on ratings/apps.py
> +    name = "ratings"
`verbose_name="Рейтинг"` или другое, по смыслу.

2024-01-26 20:38 UTC, Reagent992 commented on ratings/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
Я бы выбрал `on_delete=models.SETNULL`, даже если пользователь удален, его оценка пусть "остается для статистики".

2024-01-26 20:38 UTC, Reagent992 commented on ratings/models.py
> +        ordering = ("-content_type",)
А зачем сортировка по content_type?

2024-01-26 20:38 UTC, Reagent992 commented on ratings/models.py
> +        verbose_name_plural = "Оценка"
verbose_name_plural = `Оценки` может?

2024-01-26 20:38 UTC, Reagent992 commented on tasks/models.py
> +        related_name="task_executor",
Мне больше нравится старый `related_name`
`Пользователь.задачи.все()`
логичнее чем
`Пользователь.задача_исполнитель.все()`

2024-01-26 20:38 UTC, Reagent992 commented on tasks/models.py
> +        verbose_name_plural = "Задачa"
`verbose_name_plural = "Задачи"`
Множественное число правильно было написано же.

2024-01-26 20:38 UTC, Reagent992 commented on api/v1/permissions.py
> +# #                 user_id=executor_id,
С этим поторопился, я упростил User, придется чуть-чуть переписать. 😂
Скоро сделаю PR Тоже.

2024-01-26 20:38 UTC, Reagent992 commented on api/v1/urls.py
> +    path(
`TaskRatingCreateView` и `IPRRatingCreateView` почти одинаковые/
Наверняка можно сделать это одним эндпоинтом и одним классом. 
Но тут надо думать 🫠

2024-01-26 20:38 UTC, Reagent992 commented on api/v1/views/ratings_view.py
> +            task = Task.objects.get(id=task_id)
тут наверно можно применить `get_object_or_404`

2024-01-26 20:38 UTC, Reagent992 commented on config/settings.py
> +RATING_CHOICES = (
Тут что-то с кодировкой? 
Я вижу `"1 Ð·Ð²ÐµÐ·Ð´Ð°"`

2024-01-27 10:56 UTC, greenpandorik commented on ratings/models.py
> +        ordering = ("-content_type",)
Убрал её, добавил случайно из черновика

2024-01-27 10:56 UTC, greenpandorik commented on ratings/models.py
> +        verbose_name_plural = "Оценка"
Согласен

2024-01-27 13:55 UTC, greenpandorik commented on api/v1/urls.py
> +    path(
Сделал унаследования от классов, от главного класса.

2024-01-27 14:01 UTC, closed without merging