Create api files for IPR
Reagent992/ipr-hackathon-yandex-alfa pull request #38
Opened 2024-01-29 19:25 UTC by Arti1946

2024-01-29 21:03 UTC, Reagent992 requested changes
Хорошая работа 💪
Оставил несколько комментариев и вопросов.

Скажи мне что у тебя по времени, фронтенд уже пробует подключатся к беку, этот PR желательно не затягивать.

2024-01-29 21:36 UTC, Reagent992 commented
Еще, т.к. проект уже на  сервере:
1. PR делаем в dev
2. Есть изменения в моделях -> нужен новый файл миграции. ( внимательно, от файла миграции который сейчас есть в dev )

2024-01-30 15:22 UTC, Reagent992 approved these changes

2024-01-30 16:21 UTC, Arti1946 commented on api/v1/serializers/api/ipr_serializers.py
> +        return obj.status
мне тогда пока оставить как есть? как появятся сигналы поменяю

2024-01-30 16:26 UTC, Reagent992 commented on api/v1/serializers/api/ipr_serializers.py
> +        return obj.status
ок

2024-01-30 16:35 UTC, Reagent992 commented on api/v1/serializers/api/ipr_serializers.py
> +    status = serializers.SerializerMethodField()
В смысле, у тебя же для создания ИПР другой сериализатор.

2024-01-30 16:44 UTC, Arti1946 commented on api/v1/serializers/api/ipr_serializers.py
> +    status = serializers.SerializerMethodField()
Да, а этот для отображения при GET запросе, при создании статус ставится автоматически в работе

2024-01-30 18:54 UTC, Arti1946 commented on api/v1/serializers/api/ipr_serializers.py
> +    status = serializers.SerializerMethodField()
Все понял, затупил

2024-01-30 20:58 UTC, Reagent992 requested changes
Отлично⭐

Если у тебя нету аргументов в пользу глобального фильтра, то стоит убрать.
Остальное по желанию.

2024-01-30 20:58 UTC, Reagent992 commented on config/settings.py
> +    'DEFAULT_FILTER_BACKENDS': [
https://ilyachch.gitbook.io/django-rest-framework-russian-documentation/overview/navigaciya-po-api/filtering#nastroika-bekendov-filtrov
Это установка фильтра глобально.
Зачем?

2024-01-30 20:58 UTC, Reagent992 commented on api/v1/views/ipr_views.py
> +        if self.request.method in permissions.SAFE_METHODS:
У нас весь проект на `IsAuthenticated`, можно сократить до:
```python
        if self.request.method not in permissions.SAFE_METHODS:
            self.permission_classes = [TeamBossPermission]
        return super(IPRViewSet, self).get_permissions()
```

2024-01-30 20:58 UTC, Reagent992 commented on api/v1/views/ipr_views.py
> +        permission_classes=[permissions.IsAuthenticated],
Тут тоже можно не указывать `permission_classes=[permissions.IsAuthenticated],`

2024-01-30 20:58 UTC, Reagent992 commented on api/v1/views/ipr_views.py
> +        if self.request.method == "POST" or self.request.method == "PATCH":
Можно короче:
```python
if self.request.method in ("POST", "PATH"):
```

2024-01-30 20:58 UTC, Reagent992 commented on core/statuses_for_ipr_tests.py
> +
Название файла с ложным смыслом, это не единственное его использование.
Предлагаю просто оставить `статусы`

2024-01-30 20:58 UTC, Reagent992 commented on ipr/admin.py
В админку тоже можно вернуть `creation_date`

2024-01-31 12:52 UTC, Arti1946 commented on config/settings.py
> +    'DEFAULT_FILTER_BACKENDS': [
согласен

2024-01-31 12:55 UTC, Reagent992 approved these changes

2024-01-31 12:57 UTC, merged

2024-01-31 13:11 UTC, greenpandorik commented on api/v1/serializers/api/ipr_serializers.py
> +        return obj.status
Да, сегодня скорее всего добью это. Сорри приболел просто , выпал на пару дней