Feature/tasks signals
Reagent992/ipr-hackathon-yandex-alfa pull request #46
Opened 2024-02-01 09:08 UTC by greenpandorik

2024-02-01 10:22 UTC, Reagent992 requested changes

2024-02-01 10:22 UTC, Reagent992 commented on comments/migrations/0002_initial.py
> -# Generated by Django 5.0.1 on 2024-01-27 21:31
В этом PR должен быть только 1 файл миграций с изменениями в модели tasks.
Всего остального связанного с миграциями тут не должно быть.
Особенно не должно быть удаления уже существующих файлов.

2024-02-01 10:22 UTC, Reagent992 commented on api/v1/views/task.py
> +        executor_id = self.request.data.get("executor")
Исполнитель просто передается как id в теле POST запроса.
24 и 25 строки выглядят ненужными.

2024-02-01 10:22 UTC, Reagent992 commented on api/v1/tests/__init__.py
Это что за перемещение файла, тут этого не должно быть.

2024-02-01 10:22 UTC, Reagent992 commented on tasks/tests.py
> -            status=TaskStatus.IN_PROGRESS,
Тебе надо было просто изменить статусы в 5 местах, не надо удалять все тесты.

2024-02-01 14:09 UTC, Reagent992 commented
Еще нужно сделать `merge dev`

2024-02-01 17:01 UTC, greenpandorik commented on tasks/tests.py
> -            status=TaskStatus.IN_PROGRESS,
Менял статус везде в тестах, они не проходят постоянно ругается на django.db.utils.IntegrityError: UNIQUE constraint failed: ipr_ipr.id
Поэтому и ищу щас рпешение этой проблемы

2024-02-01 20:03 UTC, greenpandorik commented on tasks/tests.py
> -            status=TaskStatus.IN_PROGRESS,
Эти тесты пофиксил остались для эндпоинтов

2024-02-02 06:41 UTC, greenpandorik commented
1.Доделал тесты для эндпоинта Tasks

2024-02-02 11:07 UTC, closed without merging